export const FETCH_ALL_PROPERTIES = 'FETCH_ALL_PROPERTIES';
export const GET_PROPERTY_CLICKED = 'GET_PROPERTY_CLICKED';
export const GET_VIEW_TO_DISPLAY = 'GET_VIEW_TO_DISPLAY';
export const IS_LOADED = 'IS_LOADED';
export const IS_SINGLE_PROP_LOADED = 'IS_SINGLE_PROP_LOADED';